# Generated by Django 5.2.6 on 2025-09-24 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_libro_usuario_delete_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='created',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='updated',
        ),
        migrations.AddField(
            model_name='libro',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(default='Sin editorial', max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(default='Sin autor', max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=200),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.libro')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
