# Generated by Django 5.2.6 on 2025-09-25 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_libro_created_remove_libro_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='codigo_estudiante',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estudiante', models.CharField(default='0000', max_length=20)),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('fecha_devolucion', models.DateField()),
                ('estado', models.CharField(default='Bueno', max_length=100)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.libro')),
            ],
        ),
    ]
