# Generated by Django 5.2.6 on 2025-09-25 01:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_prestamo_codigo_estudiante_devolucion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='entregado',
            new_name='devuelto',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='nombre_estudiante',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='fecha_devolucion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='nombre_estudiante',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
