# Generated by Django 5.2.6 on 2025-09-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_notificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='leida',
            new_name='leido',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='codigo_estudiante',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='nombre_estudiante',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.CharField(max_length=255),
        ),
    ]
